---
apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # what kind of service/object you want to create

# what you like to call it - name the service/object

metadata:
  name: nginx-deployment # naming the deployment

spec:
  selector:
    matchLabels:
      app: nginx
  # create replica set with instances/pods
  replicas: 3
  # template to use it's label for K8 service to launch in browser
  template:
    metadata:
      labels:
        app: nginx # thish label conncects to the service
    # define container spec
    spec:
      containers:
        - name: nginx
          image: moeshaa123/130-nginx # use the image you bulit
          ports:
            - containerPort: 80
# create a kubernetes nginx-service.yml fir k8 service to launch in browser
